### ISSUE TITLE
[💡Question] 1주차_p29_HDD가 아닌 메모리에 데이터를 저장하는 DBMS알려주실 수 있나요

### ISSUE THREAD

**Issue by juhee77** [code-appender/sql-level-up#1]
### ❓이런 내용이 궁금해요.

>
HDD가 아닌 메모리에 데이터를 저장하는 DBMS알려주실 수 있나요?
대게 많은 경우 HDD를 데이터 저장소로 사용한다고 하는데 Redis와 같은 인 메모리데이터 베이스로 다른 종류도 있는지 궁금합니다.

**Comment by dlrjs2360** [comment]
메모리에 데이터를 저장하는 DBMS는 In-Memory Database (IMDB) 또는 Main-Memory DBMS (MMDB)라고 부릅니다.

말씀해주신 Redis도  메모리에 데이터를 저장하지만 MySQL과 MariaDB도 Memory 엔진을 자체적으로 가지고 있어서 메모리에 데이터를 저장할 수 있습니다.

MySQL을 예시로 들어보면 아래와 같은 방식으로 테이블에 엔진을 명시해줄 수가 있습니다.

```sql
CREATE TABLE example (
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(50),
    PRIMARY KEY (id)
) ENGINE=MEMORY;
```

또는 아래와 같이 기존 테이블의 엔진을 수정할 수도 있습니다.
```sql
alter table table_name engine=memory;
```

하지만 이렇게 메모리 엔진을 사용하기 전에는 필수적으로 버퍼 사이즈를 조절하는 과정이 필요하다고 합니다. 
![image](https://github.com/code-appender/sql-level-up/assets/81156109/3a4e7b4c-638f-4047-8183-d96c4fcd76d0)

```sql
[mysqld]
default_storage_engine=InnoDB
innodb_buffer_pool_size=256M
```

제가 이해한 질문과 답변 내용이 맞는지 애매한 느낌이 살짝 드네요. 혹시 이 답변이 맞을까요?? 🥲
