### ISSUE TITLE
[💡Question] 10주차_357p_카디널리티

### ISSUE THREAD

**Issue by dlrjs2360** [code-appender/sql-level-up#104]
### ❓이런 내용이 궁금해요.

카디널리티가 높은 필드를 인덱스로 사용해야 하는 이유는 이해가 되었는데 만약 카디널리티가 낮은 필드를 인덱스로 사용하게 되면 어떤 동작 과정으로 탐색이 이루어지는지 궁금합니다.
정리하자면 인덱스를 잘못 선택하면 탐색 속도가 왜 느려지는지에 대한 실질적인 원리를 알고 싶습니다.

**Comment by juhee77** [comment]
카디널리티가 낮은 인덱스를 선택하는 경우는 값의 중복이 많기 떄문에 특정 값을 찾는데 효과적이지 않을 수 있습니다. (즉 거의 테이블 전체를 스캔하는것과 유사하게 진행될 수 있습니다)

B+tree의 인덱스를 확인하는 경우 값의중복이 많다면 일치하는 값들이 많아지게 되고 오히려 인덱스를 사용한는것이 비효율적일수 있습니다. 이런 경우 옵티마이저가 인덱스를 전체 테이블을 스캔하게 될 수 있고 인덱스를 사용하는것보다 더 많은 I/O작업이 일어날 수 있어 성능이 떨어집니다. 

또한 B+tree내에서 동일한 값을 찾은후 링크드 리스트로 연결된 노드를 따라가면 계속하여 진행하기에 오히려 비효율적일 수 있습니다. (추가적인 노드 탐색이 많다)
