### ISSUE TITLE
[💡Question] 10주차_363p_like 인덱스

### ISSUE THREAD

**Issue by dlrjs2360** [code-appender/sql-level-up#105]
### ❓이런 내용이 궁금해요.

like를 사용하는 경우 전방 일치(대공원%)에만 인덱스를 적용할 수 있는 이유가 궁금합니다.

**Comment by juhee77** [comment]
BTree의 특징상 자식 노드의 데이터들은 노드 데이터를 기준으로 왼쪽에서 오른쪽으로 작은값 큰값이 정렬되어있습니다. 
즉 인덱스의 작동방식과 특성에 의헤 전방 일치에만 인덱스를 적용할 수 있습니다.

따라서 특정 값으로 시작하는 데이터를 찾는 것은 쉽지만, 특정 값으로 끝나는 데이터를 찾는 것은 어려워집니다. '%' 와일드카드가 앞에 위치하는 경우에는 검색 대상이 모든 값으로 시작하는 것이기 때문에, B+ 트리에서는 해당 검색을 효율적으로 처리할 수 없습니다. 따라서 Like연산이 사용될때 인덱스를 사용하고자 한다면 전방일치하여 찾는데이터가 많은 경우에만 인덱스를 생성하는 것이 좋습니다.
