### ISSUE TITLE
[💡Question] 1주차_bonus_REDO와 UNDO 동작 과정

### ISSUE THREAD

**Issue by juhee77** [code-appender/sql-level-up#17]
### ❓이런 내용이 궁금해요.

>
REDO와 UNDO 동작 과정

**Comment by dlrjs2360** [comment]
redo 작업과 undo 작업은 데이터 복구 방향과 방법에서 완전히 반대입니다.

## 작업이 발생하는 시점
redo 작업은 트랜잭션 커밋이 완료된 이후 시스템에 장애가 발생했을 때 복구 작업을 진행합니다.
이에 반해, undo 작업은 트랜잭션 커밋이 진행되는 도중에 트랜잭션이 실패했을 때 진행됩니다.

## 복구 방향
undo와 redo 모두 복구 작업 이전의 상태를 되돌립니다.

redo 로그 파일에는 이전 상태, 변경 작업, 이후 상태라는 데이터가 존재하고 복구 작업이 진행되면 이전 상태 환경에서 변경 작업을 다시 수행해서 이후 상태를 만들어냅니다. 만약 A라는 상태에서 B라는 작업을 수행해서 C를 만드는 작업이 가장 최근 작업이라면 시스템 장애 발생 시 DBMS는 A라는 시스템 환경에서 B 작업을 그대로 다시 수행해서 C를 만들어냅니다.

undo 로그 파일은 위와 똑같은 상황에서 B라는 작업 이전의 상태인 A를 저장하고 있습니다. 따라서 트랜잭션 실패 시 A로 되돌리기만 하면 되는 것입니다.

이러한 이유로 두 복구 작업은 방향이 반대라고 할 수 있습니다. redo는 B -> (시스템 장애) ->  A -> B 이고 undo는 B(트랜잭션 실패)-> A 입니다.
