### ISSUE TITLE
[💡Question] 1주차_p34_메모리 로그정보에 갱신관련 정보를 저장한 이후에 커밋으로 갱신처리를 확정하는 과정

### ISSUE THREAD

**Issue by juhee77** [code-appender/sql-level-up#2]
### ❓이런 내용이 궁금해요.

>
메모리 로그정보에 갱신관련 정보를 저장한 이후에 커밋으로 갱신처리를 확정하는 과정에서 실제 CRUD시에 관련 정보를 확정하면 반드시 디스크에 접근하여 해당 처리를 완료했다고 작성하는것이 맞는걸까요

즉 갱신처리시에 관련정보는 단순히 로그파일에 기록하여 처리하고 이후에 실제 데이터 베이스에 처리하면 그 이후에 디스크에 로그정보와 관련된 데이터에 해당 내용을 저장하는것을 커밋이라고 하는게 맞는건지 궁금합니다.

**Comment by dlrjs2360** [comment]
질문이 조금 헷갈리는데 "변경 사항을 저장소가 아닌 로그 파일에만 기록하는 것이 커밋이 맞는가"를 말씀하시는 게 맞을까요? 다시 말하면 실제 저장소에 저장이 되어야 커밋인지, 로그파일에 기록되기만 해도 커밋이 되는 것인지를 말씀하시는 게 맞을까요??

**Comment by dlrjs2360** [comment]
일단 제가 이해한 내용대로 답변을 적어보겠습니다.

DBMS에서 트랜잭션이 커밋되었다고 판단되는 기준은 해당 트랜잭션의 변경 사항이 모두 디스크에 안전하게 저장되었음을 보장할 수 있을 때입니다. 이를 보장하기 위해 대부분의 DBMS는 WAL(Write-Ahead Logging)이라는 기법을 사용합니다.

WAL 기법에 따르면 트랜잭션의 변경 사항이 redo 로그 파일로 완전히 기록되었을 때, 그 트랜잭션은 커밋되었다고 판단됩니다.

즉, 트랜잭션의 커밋이 완료되었다는 것은 해당 트랜잭션의 변경 사항이 모두 redo 로그 파일에 기록되었으며, 이로 인해 데이터베이스의 무결성이 보장되었음을 의미합니다. 이는 시스템 장애가 발생하더라도 redo 로그 파일의 내용을 사용하여 데이터베이스를 복구할 수 있게 합니다.

결론적으로, 커밋이 되었다는 것은 데이터가 디스크에 완벽하게 기록되었음을 의미하지만 해당 변경사항이 저장소에 전부 적용이 되었다는 것을 의미하지는 않습니다. 변경 사항은 데이터 페이지라는 공간에 기록되었다가 커밋이 완료된 이후에도 저장소에 반영이 될 수 있습니다.
