### ISSUE TITLE
[💡Question] 2주차_83p_뷰 생성 시 컬럼

### ISSUE THREAD

**Issue by dlrjs2360** [code-appender/sql-level-up#20]
### ❓이런 내용이 궁금해요.

뷰를 생성할 때, 컬럼을 제대로 지정하지 않으면 어떻게 되는지 궁금합니다! 예를 들어, 뷰에서 작성한 SELECT 구문의 컬럼은 3개인데 뷰에서는 2개를 작성해서 개수가 맞지 않는다면 어떻게 되는지 궁금해요.

**Comment by ranunclulus** [comment]
저도 궁금해서 예제에 있는 데이터들을 local에 넣고 view를 만들어 보았더니 다음과 같은 에러가 발생했습니다.
<img width="1512" alt="image" src="https://github.com/code-appender/sql-level-up/assets/87214089/d417429e-93cd-4631-8eaa-1850298622a4">
Maria DB 공식 문서에서 1353 오류를 살펴보니 뷰의 정의 자체가 테이블 표현식에서 select 목록 개수와 열 이름 개수가 동일해야지만 생성됩니다. 
<img width="765" alt="image" src="https://github.com/code-appender/sql-level-up/assets/87214089/8a3ccb77-669f-4628-9575-b6f7fc17a7db">

[공식 사이트](https://mariadb.com/kb/en/mariadb-error-code-reference/)
