### ISSUE TITLE
[💡Question] 2주차_84p_익명 뷰와 서브 쿼리의 차이

### ISSUE THREAD

**Issue by dlrjs2360** [code-appender/sql-level-up#21]
### ❓이런 내용이 궁금해요.

책을 읽어봐도 익명 뷰랑 서브 쿼리의 차이점이 뭔지 잘모르겠습니다. 두 개가 다른 건가요??

**Comment by ranunclulus** [comment]
서브쿼리는 말 그대로 (sub) 부가적인 쿼리, 하위 쿼리의 개념입니다. 서브쿼리가 들어갈 수 있는 위치는 다음과 같습니다.
- SELECT 절
- FROM 절
- WHERE 절
- HAVING 절
- ORDER BY 절
- INSERT의 VALUE 절
- UPDATE의 SET 절

```sql
INSERT (name, phone_nbr, address, sex, age)
VALUES ('희수', '010-0000-0000', (SELECT address FROM Address WHERE name = '인성'), 25);
```

서브쿼리가 FROM절 안에서 사용된 경우에 익명 뷰, 인라인 뷰라고 부릅니다. 서브쿼리의 결과가 하나의 테이블에 대한 뷰처럼 사용되기 때문입니다. 인라인 뷰를 사용할 때는 서브쿼리의 결과에 대해 뷰를 이름인 가명을 지정해 줘야 합니다.
```sql
SELECT v_address, cnt
FROM (SELECT address AV v_address, COUNT(*) AS cnt FROM Address)
AS CountAddress;
```

**Comment by juhee77** [comment]
서브쿼리 >= 인라인뷰

**Comment by Jyoungjo** [comment]
인라인뷰 ⊂ 서브쿼리
:)
