### ISSUE TITLE
[💡Question] 2주차_p_83_뷰 사용으로 인한 성능차이가 있는지 궁금합니다!

### ISSUE THREAD

**Issue by Jyoungjo** [code-appender/sql-level-up#22]
### ❓이런 내용이 궁금해요.

뷰를 사용했을 때, 복잡한 구문을 단순하게 사용할 수 있도록 해주는 것임을 알 수 있는데 뷰에서 데이터를 선택하는 과정에서 다시 해당 테이블로 돌아가 쿼리문을 실행시키는 거 같아서 성능적으로 어떻게 차이가 있는지 궁금합니다!

**Comment by ranunclulus** [comment]
뷰를 사용하는 이유는 성능적인 향상도를 기대하는 것보다는 데이터 보안과 사용자의 편리함을 위해서입니다. 만약 뷰로 생성된 내용을 테이블로 저장하게 된다면 데이터 저장 공간에 대한 비용이 발생하게 됩니다. 이미 구성된 원본 테이블로 뷰의 내용을 모두 구성할 수 있는 경우 데이터 저장 공간과 SQL문 계산 속도에 따른 트레이드 오프를 반영해 프로젝트마다 조정하는 것이 가장 좋은 방법이라고 할 수 있습니다.

또한 뷰를 사용하는 경우 원본 테이블에 직접적으로 접근하지 않고 임의의 뷰를 사용하기 때문에 해당 데이터에 대한 보안이 강화됩니다. 또한 복잡한 쿼리문을 반복해서 작성할 필요가 없다는 장점을 채택해 뷰를 사용합니다.
