### ISSUE TITLE
[💡Question] 주차_p_83_뷰를 실제로 사용하는지?

### ISSUE THREAD

**Issue by YunByungil** [code-appender/sql-level-up#27]
### ❓이런 내용이 궁금해요.  
뷰를 실제로 사용하는지 궁금합니다.  
뷰에 관한 내용을 이번에 처음 알았는데, 실무나 프로젝트에 사용하는지 알려주세요.

>

**Comment by ranunclulus** [comment]
view는 사용자의 편의와 데이터베이스의 보안 때문에 사용합니다. 원본 테이블에 직접 접근하지 않아도 임의의 뷰를 구성하여 별도의 이름을 붙이거나 접근 가능한 사람을 지정할 수 있기 때문입니다. 따라서 실무에서는 권한에 따라 사용자가 접근할 수 있는 테이블이나 뷰가 다를 수 있습니다. 실제 데이터베이스 운영 환경에서는 보안과 성능 문제 때문에 모든 사용자에게 전체 테이블을 공개하지 않을 수도 있기 때문에 뷰를 활용해서 사용자에게 적합한 가상 테이블을 만들어 제공하기도 합니다.
