### ISSUE TITLE
[💻Code] 2주차_p89_Case식 예시

### ISSUE THREAD

**Issue by juhee77** [code-appender/sql-level-up#28]
### ❓이런 코드가 필요해요.

>
Case식이 Select, where, group by, having, orderby등에 사용 가능하다고 하는데 어떻게 사용되는지 예시 코드가 궁금합니다!

**Comment by ranunclulus** [comment]
- SELECT
<img width="1512" alt="image" src="https://github.com/code-appender/sql-level-up/assets/87214089/f6eea984-42a4-463a-95f2-eed82e55f368">

- WHERE
<img width="1512" alt="image" src="https://github.com/code-appender/sql-level-up/assets/87214089/bdfaae99-b6e4-4794-be81-34d956b2b8c1">

- ORDER BY
<img width="1512" alt="image" src="https://github.com/code-appender/sql-level-up/assets/87214089/659dea4a-3e8e-4e04-b20a-ac80a84774c5">

등등이 있습니다.

**Comment by ranunclulus** [comment]
WHERE -> END = 0 (조건의 여집합만 출력)
ORDER BY -> END = 0 (선택 데이터 중 null값이 있는 로우 제거)

**Comment by ranunclulus** [comment]
END에 대한 내용 추가하기
