### ISSUE TITLE
[💡Question] 2주차_p91_데이터 중복 제거 기술

### ISSUE THREAD

**Issue by juhee77** [code-appender/sql-level-up#29]
### ❓이런 내용이 궁금해요.

>
질문이 너무 조잡하면 생략하셔도 됩니당
91페이지에 중복 제거 내용이 있어서 질문드립니당
혹시 데이터 베이스 내부적으로 중복제거는 어떻게 진행하는지 알려주실 수 있나요?

**Comment by ranunclulus** [comment]
MySQL이 내부적으로 중복이라고 판단하는 기준은 이렇게 설명할 수 있습니다. UNION 계산은 이미 SELECT 구문을 진행한 뒤에 중복 제거를 진행합니다. 따라서 SELECT 되기 전에 테이블이나 레코드에 대한 정보가 아닌 SELECT 된 튜플들에 속해 있는 정보를 기준으로 중복 유무를 판단합니다. 모든 칼럼의 값 자체가 중복 체크의 기준이 되는 것입니다.
SQL 내부적으로 UNION을 처리하는 과정은 다음과 같습니다.
1. 최종 UNION 결과에 적합한 임시 테이블을 메모리 테이블로 생성합니다.
2. 임시 테이블의 모든 칼럼으로 Unique Hash 인덱스를 생성합니다.
3. 같은 값은 같은 index를 가지게 되기 때문에 Hash 인덱스를 생성하는 과정에서 중복 제거가 일어납니다
4. 이후 임시 테이블 결과를 읽어서 전송하고 임시 테이블을 삭제합니다.

**Comment by juhee77** [comment]
결론 -> 중복 제거 기술이 필요하지 않은경우 UNION ALL을 사용하는것이 성능적인 측면에서 이득이다.
