### ISSUE TITLE
[💡Question] 3주차_117p_CASE 식에서의 pop

### ISSUE THREAD

**Issue by dlrjs2360** [code-appender/sql-level-up#38]
### ❓이런 내용이 궁금해요.

코드 3-4를 보면 
`SUM(CASE WHEN sex = '1' THEN pop ELSE 0 END)` 라고 나와 있습니다.

여기서 pop이라는 게 제가 생각하는 빼는 pop인 것인지 혹시 저 자리에 어떤 키워드가 더 들어갈 수 있는지 궁금합니다.

**Comment by juhee77** [comment]
이거 뭔가 느낌이 그 컬럼값 이름이 pop이라서 저렇게 되는거 같아용(추측상..?)

**Comment by dlrjs2360** [comment]
헉 그런가봐요... 아주 어리석은 질문이었군요.. 바로 닫아버리겠습니다.
