### ISSUE TITLE
[💡Question] 5주차_164p_코드해석 필요

### ISSUE THREAD

**Issue by dlrjs2360** [code-appender/sql-level-up#59]
### ❓이런 내용이 궁금해요.

164p에 나온 코드가 어떤 원리로 동작하는지 하나두 모르겠습니다...
한 문장씩 해석보다는 코드 전체적인 흐름으로 어떤 방식으로 진행되는 것인지 아주 간단하게만 설명해주시면 감사하겠습니다.

**Comment by juhee77** [comment]
```
CREATE OR REPLACE PROCEDURE PRO_INSERT_VAR
IS
  CURSOR c_sales IS
    SELECT company, year, sale
    FROM Sales
    ORDER BY company.year;

  rec_sales c_sales%ROWTYPE;

  i_pre_sale INTEGER := 0;
  c_company CHAR(1) := '*';
  c_var CHAR(1) := '*';

BEGIN
  OPEN c_sales;
  LOOP
    FETCH c_sales INTO rec_sales;
    EXIT WHEN c_sales%NOTFOUND;

    IF (c_company = rec_sales.company) THEN
      IF (i_pre_sale < rec_sales.sale) THEN
        c_var := '+';
      ELSIF (i_pre_sale > rec_sales.sale) THEN
        c_var := '-';
      ELSE
        c_var := '=';
      END IF;
    ELSE
      c_var := NULL;
    END IF;

    INSERT INTO Sales2(company, year, sale, var)
    VALUES (rec_sales.company, rec_sales.year, rec_sales.sale, c_var);

    c_company := rec_sales.company;
    i_pre_sale := rec_sales.sale;
  END LOOP;

  CLOSE c_sales;
  COMMIT;
END;
```

먼저 CREATE 부분에서 프로시저를 생성합니다(REPLACE가 있어 기존에 존재하는 경우 덮어씀)
즉 프로시저를 구성하는 코드입니다.
IS : 프로시저 정의를 시작합니다 

프로시저의 동작을 적의합니다.
BEGIN : 실행 블록의 시작을 나타냅니다. 
LOOP : 무한 루프가 시작됩니다. 
END LOOP : 루프의 종료 위치입니다. 
END : 프로시저의 끝을 선언합니다. 

즉 프로시저 내에서 커서를 선언하여 테이블 내에 어떤 열의 가져올지 정의하고 이를 비교하기 위해 사용합니다.
또한 카운터의 의미는 루프내에서 사용되는 변수를 의미합니다.  (책의 주석 부분 내용)
LOOP 내에서는 커서에서 가져온 데이터를 바탕으로 이전에 저장한 데이터와 비교하며 Sales2 테이블에 비교된 데이터의 결과를 삽입합니다. 이후 데이터 처리가 완료되어  레코드가 없다면 루프가 종료되면 커서(c_sales)를 닫고 트랜잭션을 커밋하는것입니다. 

또한 그 중에서 `c_company := rec_sales.company ` 와 같은 부분은 현재 반복 처리중인 데이터의 값을 c_company에 할당하여 이전 처리한 데이터와의 비교를 위해 사용하는것입니다. 


<details>
  <summary>여기까지가 내용이고 추가적으로 한줄씩 설명하면 다음과 같습니다. ( gpt )</summary>  
### 프로시전 선언부
CREATE OR REPLACE PROCEDURE PRO_INSERT_VAR: 저장 프로시저 "PRO_INSERT_VAR"를 생성하거나 이미 존재하면 덮어쓰기 위한 선언.
IS: 저장 프로시저의 시작을 나타내는 키워드.
CURSOR c_sales IS ... : "c_sales"라는 이름의 커서를 정의. 이 커서는 "Sales" 테이블에서 company, year, sale 열을 가져오고 company 열의 값에 따라 정렬한다.
rec_sales c_sales%ROWTYPE: "c_sales" 커서의 행 타입과 동일한 구조를 갖는 레코드를 정의.
i_pre_sale INTEGER := 0: 정수형 변수 "i_pre_sale"을 0으로 초기화.
c_company CHAR(1) := '*';: 문자형 변수 "c_company"를 '*'로 초기화.
c_var CHAR(1) := '*';: 문자형 변수 "c_var"를 '*'로 초기화. 

### 프로시저 동작부
BEGIN: 실행 블록의 시작을 나타내는 키워드.
OPEN c_sales;: "c_sales" 커서를 열어서 데이터를 가져올 수 있도록 함.
LOOP: 무한 루프 시작.
FETCH c_sales INTO rec_sales;: "c_sales" 커서에서 데이터를 가져와 "rec_sales" 레코드에 저장.
EXIT WHEN c_sales%NOTFOUND;: "c_sales" 커서가 더 이상 행을 찾지 못하면 루프를 빠져나감.
IF (c_company = rec_sales.company) THEN ... END IF;: 현재 데이터의 company 값이 이전에 저장한 c_company 값과 동일한지 확인.
IF (i_pre_sale < rec_sales.sale) THEN ... END IF;: 현재 sale 값이 이전에 저장한 i_pre_sale 값보다 큰지 확인.
ELSE IF(i_pre_sale > rec_sales.sale) THEN ... END IF;: 현재 sale 값이 이전에 저장한 i_pre_sale 값보다 작은지 확인.
ELSE: 위의 조건들이 모두 만족하지 않는 경우.
INSERT INTO Sales2 ... : Sales2 테이블에 데이터를 삽입.
c_company := rec_sales.company;: 현재 데이터의 company 값을 저장.
i_pre_sale := rec_sales.sale;: 현재 데이터의 sale 값을 저장.
CLOSE c_sales;: "c_sales" 커서를 닫음.
COMMIT;: 트랜잭션을 커밋하여 변경 사항을 영구적으로 저장.
END;: 실행 블록의 끝을 나타내는 키워드.
</details>

**Comment by dlrjs2360** [comment]
왓...이렇게 빡세게 적어주실줄은 몰랐습니다...아주 수고하셨습니다..
