### ISSUE TITLE
[💡Question] 5주차_185p_윈도우 함수를 사용한 방법

### ISSUE THREAD

**Issue by YunByungil** [code-appender/sql-level-up#60]
### ❓이런 내용이 궁금해요.

>
185에서 윈도우 함수를 사용하는데, 제가 이해한 내용은 case when을 이용하면 모든 경우를 다 탐색하는 반복계이고  
윈도우 함수를 사용하여 스캔횟수를 줄이는게 맞는 건가요?  
185p에서 나오는 코드 조금 쉽게 설명해주실 수 있나요?

**Comment by juhee77** [comment]
윈도우 함수는 특정 윈도우에서 데이터에 접근하고 분석하여 전체 데이터 집합에 반복적으로 접근하지 않아도 되어서 유리한게 맞습니다. 
또한 CASE WHEN절은 각 행의 조건을 평가하여 데이터를 순회하면 탐색하는 반복계가 맞습니다. 

코드 5-8은 FROM 절 내부 부터 설명하겠습니다.   
첫 번째 CASE WHEN에서 pcode에 따른 hit_code를 계산합니다. 이후 윈도우 함수중 MIN함수를 통해 hit_code값들중의 최소값을 찾습니다. 이후 over 절에서 hit_code를 순서로 정렬하여 윈도우를 생성합니다.   

이렇게 한 이후 외부 쿼리에 의해 hit_code 와 같은 min_code를 찾아 값을 출력합니다.   

즉 이렇게 하여 각 우체번호에 따라 코드를 부여하고 코드중 가장 작은 값에 대해서만 같은 데이터를 출력하도록 합니다.(즉 가장 작은 값이 여러개인 경우는 여러개의 로우를 출력합니다)
