### ISSUE TITLE
[💡Question] 6주차_p224_Nested Loops

### ISSUE THREAD

**Issue by YunByungil** [code-appender/sql-level-up#69]
### ❓이런 내용이 궁금해요.

>
구동 테이블로 큰 테이블을 선택하는 역설적인 방법이 이해가 안 됩니다.  
기존 방식과 역설적인 방법을 비교했을 때, 더 나아진다는 예시를 보여주실 수 있나요?  
이번 파트는 어떤 질문을 해야 할지 감이 안 오네요..

**Comment by dlrjs2360** [comment]
많은 레퍼런스를 찾아봐도 정확한 설명은 없어서 제가 이해한 내용으로 설명드리겠습니다.

A와 B 테이블이 있고 A가 작은 테이블, B가 큰 테이블입니다. A는 레코드가 5개 B는 10개 입니다.
책에 나온대로 작은 테이블을 구동 테이블로 선택하고 큰 테이블을 내부 테이블로 선택했습니다.

NL 특성상 A의 한 레코드 씩 탐색을 진행하게 되는데 한 레코드당 매칭되는 B의 레코드가 5개입니다. 그렇게 되면 시간복잡도는
`A의 레코드 수 (5) * 레코드 당 매칭되는 B의 레코드 수 (5)` 이므로 25가 됩니다.

하지만 만약에 여기서 B를 구동 테이블로 선택한다면 어떨까요?
하나의 B당 하나의 A가 선택된다면 시간복잡도는
`B의 레코드 수 (10) * 레코드 당 매칭되는 A의 레코드 수 (1)` 이므로 10이 됩니다.

조금 극단적인 예시이지만 책에서 말하고자 하는 내용은 이 예시라고 생각합니다.

결국 중요한 것은 레코드 당 매칭되는 내부 테이블의 레코드가 얼마인지이며  이 과정 또한 인덱스가 어떻게 설정되는지에 따라 달라질 수 있습니다.
