### ISSUE TITLE
[💡Question] 1주차_p_34_로그 파일에 전달된 갱신 정보가 사라질수도 있나요?

### ISSUE THREAD

**Issue by Jyoungjo** [code-appender/sql-level-up#7]
### ❓이런 내용이 궁금해요.

>
해당 페이지에서 로그 파일에 전달된 갱신 정보가 DBMS가 다운될 때 사라지는 현상에 대해 설명을 하고 있는데

로그 파일에 갱신 정보가 저장되었다면 커밋이 실행이 된 후 일텐데 이 정보가 사라질수도 있는건가요..?

로그 버퍼 위에 올라온 데이터가 장애로 인해 사라질 수 있다는 것은 알고 있지만, 로그 파일에 저장된 갱신 정보가 다운될 때 사라지는 현상에 대해서 잘 모르겠습니다!

**Comment by dlrjs2360** [comment]
저도 이 부분이 참 헷갈렸는데 다시 읽다 보니 말을 조금 애매하게 해놔서 그런 것 같습니다.

"로그 파일에 전달된 갱신 정보"는 로그 파일에 저장되지 않고 전달만 된 상황을 이야기 하는 것이라고 이해했습니다. 

아직 기록이 완료되지는 않았기 때문에 DBMS가 갱신을 비동기로 진행한다면 즉, redo 로그 파일에는 이미 다른 내용(A)이 있고 로그 버퍼에서 redo 로그 파일로 변경 내용(B)을 전달하고자 할 때, redo 로그 파일의 내용을 저장소에 적용하는 과정에서 장애가 발생하면 redo 로그 파일에는 아직 A 내용이 남아있기 때문에 B는 기록되지 못하고 사라지는 것입니다. 

따라서 커밋이 발생하여 로그 버퍼에 적힌 내용이 redo 로그 파일로 전달될 때에는 반드시 동기 접근이 필요해집니다. 동기 접근을 통해 B를 미리 비우고 A를 채워넣음으로써 "커밋 == 데이터 저장" 을 이뤄내는 것이죠.

사실 이 부분은 검색은 따로 해보지 않고 제 뇌피셜로 적어봤습니다... 회의 때 부족하다고 판단되면 다시 찾아보겠습니다.
