### ISSUE TITLE
[💡Question] 주차_p231_크로스결합이선택되는 경우 

### ISSUE THREAD

**Issue by juhee77** [code-appender/sql-level-up#72]
### ❓이런 내용이 궁금해요.

>
삼각결합으로 인한 크로스 결합이 실행되는 경우를 확인하기 위해서는 실행계회을 파악해야만 알 수 있는 것인지 궁금합니다.

**Comment by dlrjs2360** [comment]
알아본 바로는 실행계획을 파악하는 것 외에는 방법이 없는 것 같습니다... 옵티마이저가 판단하기 이전에 개발자가 직접 테이블 간의 관계를 확인한다고 해도 정확한 비용과 연산 순서를 계산하는 것은 어렵기 때문에 실행 계획을 먼저 확인하는 것이 최선이라고 생각합니다.

**Comment by juhee77** [comment]
감사합니다!!
