### ISSUE TITLE
[💡Question] 주차_p227_Bi/DWH가 무엇인가요

### ISSUE THREAD

**Issue by juhee77** [code-appender/sql-level-up#73]
### ❓이런 내용이 궁금해요.

>
BI/DWH가 무엇인가요?

**Comment by dlrjs2360** [comment]
BI (Business Intelligence)
비즈니스 인텔리전스는 기업에서 데이터를 수집, 정리, 분석하고 활용하여 효율적인 의사결정을 하도록 돕는 정보체계입니다.

DWH (Data Warehouse)
데이터 웨어하우스는 사용자의 의사 결정에 도움을 주기 위해서 기간 시스템의 데이터베이스에 축적된 데이터를 공통의 형식으로 변환해서 관리하는 데이터베이스입니다.

두 개념의 공통점은 대량의 데이터를 사용하고 실시간 데이터 처리가 필요하지 않다는 것입니다. 해시의 큰 장점을 살려서 대량의 데이터를 다루고 실시간 처리가 이루어지지 않아도 되는 상황에서 지연의 걱정없이 사용할 수 있기 때문에 BI/DWH와 같은 시스템에서 해시 결합이 유용하다는 것이 의도인 것 같습니다.

**Comment by juhee77** [comment]
감사합니다!!
