### ISSUE TITLE
[💡Question] 8주차_277p_mysql 갱신 서브쿼리

### ISSUE THREAD

**Issue by dlrjs2360** [code-appender/sql-level-up#94]
### ❓이런 내용이 궁금해요.

저자주에 보면 Mysql에서 갱신 SQL 내부의 서브쿼리에서는 테이블 자기 참조가 불가능하다고 나와있는데 그럼 MYSQL 순번 갱신은 윈도우 함수밖에 없는 것인지 다른 방식이 있는지 궁금합니다.

**Comment by YunByungil** [comment]
자기 참조가 불가능한 이유
MySQL은 UPDATE, DELETE 문 내에서 같은 테이블을 참조하는 서브쿼리를 사용할 때 제한을 두고 있는데,
데이터 일관성과 무결성을 유지하기 위한 것입니다.
즉, 업데이트 중에는 해당 테이블의 상태가 변할 수 있으므로 제한을 둔 것입니다.

임시 테이블 사용
MySQL 순번 갱신은 윈도우 함수말고,
임시 테이블 사용하여 해결할 수 있습니다.

![image](https://github.com/code-appender/sql-level-up/assets/109706328/4b866ba8-5b7e-40b5-ad70-8a6e1fdecdc1)

서브쿼리의 제약을 피할 수 있고, 복잡한 조건이나 대량의 데이터를 처리해야 할 때 유용할 수 있습니다.
임시 테이블을 생성하고 데이터를 삽입하는 과정에서 추가적인 시간과 자원이 소모될 수 있으므로,
성능 측면을 고려하여 사용해야 합니다.

윈도우 함수를 사용하는게 더 간단한 것 같습니다.
